module layer #(
    parameter integer IN         = 784, //num of inputs
    parameter integer OUT        = 128, //num of neurons
    parameter integer PES        = 8,
    parameter integer DATA_WIDTH = 8, //8 bit weights
    parameter integer ACC_WIDTH  = 18, //for PE accumulation
    parameter integer THRESHOLD  = 32,

    parameter MEM_FILE0 = "mem_if/fc1_weights_bank0.mem",
    parameter MEM_FILE1 = "mem_if/fc1_weights_bank1.mem",
    parameter MEM_FILE2 = "mem_if/fc1_weights_bank2.mem",
    parameter MEM_FILE3 = "mem_if/fc1_weights_bank3.mem",
    parameter MEM_FILE4 = "mem_if/fc1_weights_bank4.mem",
    parameter MEM_FILE5 = "mem_if/fc1_weights_bank5.mem",
    parameter MEM_FILE6 = "mem_if/fc1_weights_bank6.mem",
    parameter MEM_FILE7 = "mem_if/fc1_weights_bank7.mem"
)(
    input  wire                                 clk,
    input  wire                                 reset_n,
    input  wire                                 en, // controls fetching weights and PE accumulation
    input  wire                                 clear,  //clear PE accumulator
    input  wire                                 image_start_clear, //clear mem potential memory
    input  wire                                 neuron_en,
    input  wire [$clog2(IN)-1:0]                col_addr,
    input  wire [3:0]                           active_pes,
    input  wire [$clog2((OUT+PES-1)/PES)-1:0]   group, //16 groups in total, need 4 bits
    input  wire [$clog2(IN * ((OUT+PES-1)/PES))-1:0] base_addr,    //all in until here

    output wire [PES-1:0]                       spikes_out,
    output wire [PES-1:0]                       valid
);

    wire signed [DATA_WIDTH-1:0] weights [0:PES-1];
    wire signed [ACC_WIDTH-1:0]  cur     [0:PES-1]; //accumulated weighted sums coming from the PEs

    reg pe_en; //one-cycle delayed version of en

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            pe_en <= 1'b0;
        end else begin
            pe_en <= en;
        end
    end // need to account for the latency of weight registered on the clock edge when enabling the PE

    // bram sends the weights directly to PEs
    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE0))
        bram0 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[0]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE1))
        bram1 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[1]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE2))
        bram2 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[2]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE3))
        bram3 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[3]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE4))
        bram4 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[4]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE5))
        bram5 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[5]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE6))
        bram6 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[6]));

    weight_bram #(.ROWS((OUT+PES-1)/PES), .COLS(IN), .DATA_WIDTH(DATA_WIDTH), .MEM_FILE(MEM_FILE7))
        bram7 (.clk(clk), .en(en), .base_addr(base_addr), .col_addr(col_addr), .weight_out(weights[7]));

    // State memory for membrane potentials
    reg signed [ACC_WIDTH-1:0] mem_pot_array [0:((OUT+PES-1)/PES)-1][0:PES-1]; //neuron i within group, 16x8=128 storage locations, one membrane potential per neuron
    wire signed [ACC_WIDTH-1:0] mem_out_wires [0:PES-1]; //new mem potentials generated by IF neurons

    genvar i;
    generate
        for (i = 0; i < PES; i = i + 1) begin : pe_array
            wire active = (i < active_pes); //controls how many of them are active
            
            pe #(
                .DATA_WIDTH(DATA_WIDTH),
                .ACC_WIDTH(ACC_WIDTH)
            ) pe_inst (
                .clk(clk),
                .reset_n(reset_n),
                .en(pe_en & active), //PE only operates when both are 1
                .clear(clear),
                .weight(weights[i]),
                .cur_out(cur[i]),
                .valid(valid[i])
            );
        end

        for (i = 0; i < PES; i = i + 1) begin : neuron_array
            integer g; // FIX: Move iterator inside the generate block to isolate variables and prevent loop race conditions
            wire active = (i < active_pes);
            
            if_neuron #(
                .ACC_WIDTH(ACC_WIDTH),
                .THRESHOLD(THRESHOLD)
            ) neuron_inst (
                .mem_in(mem_pot_array[group][i]),
                .cur_in(cur[i]),
                .spike_out(spikes_out[i]),
                .mem_out(mem_out_wires[i]) 
            );
            
            // Sequential state updates
            always @(posedge clk or negedge reset_n) begin
                if (!reset_n) begin
                    for (g = 0; g < ((OUT+PES-1)/PES); g = g + 1) begin
                        mem_pot_array[g][i] <= 0;
                    end
                end else if (image_start_clear) begin 
                    for (g = 0; g < ((OUT+PES-1)/PES); g = g + 1) begin
                        mem_pot_array[g][i] <= 0; 
                    end
                end else if (neuron_en && active) begin
                    mem_pot_array[group][i] <= mem_out_wires[i]; //stores the new membrane potential back into the array, replacing the old values
                end
            end
        end
    endgenerate
endmodule

//the if neuron receives mem_in(historical voltage from the mem_pot_array) and cur_in(the new accumulation from the PE)
//mem_out_wires is declared as wire, so it updates all the time, which follows mem_in + cur_in